[project]
name = "pr-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gitpython>=3.1.44",
    "pyyaml>=6.0.2",
    "requests>=2.32.4",
]
